title: Minimal
email: blog@minimal.com
description: > 
  Esse é um blog minimalista para estudos com a ferramenta Jekyll
baseurl: "/minimal-blog" 
url: "" 
twitter_username: minimal_twitter
github_username:  minimal_github

# Build settings
markdown: kramdown
sass:
    sass_dir: ./_sass
permalink: :year:month/:title
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
